#
# Mile explorer backend configure

http_bind_address: "0.0.0.0"
http_port: 8042

#
# Db connection
#
db_host: "localhost"
db_port: 28015
db_name: "blockchain"

#
# Debug
#
json_rpc_debug: true

#
# Logging levels:
#
#  trace = 0,
#  debug = 1,
#  info = 2,
#  warn = 3,
#  err = 4,
#  critical = 5,
#  off = 6
#
log_level: 0
