#
# Mile indexer configure
#

#
# Scainning nodes
#
#node_urls: ["https://nyc03.t.mile.global/v1/api",
#            "https://nyc01.t.mile.global/v1/api",
#            "https://trnt01.t.mile.global/v1/api"]

node_urls: ["http://lotus000.testnet.mile.global/v1/api",
            "http://lotus001.testnet.mile.global/v1/api"]

#
# Processing options
#
request_timeout: 50 # msec.
update_timeout:  20  # sec.
rpc_queue_size:  16
block_processin_queue_size: 10

#
# Db connection
#
db_host: "localhost"
db_port: 28015
db_name: "blockchain"

#
# Debug
#
json_rpc_debug: false

#
# Logging levels:
#
#  trace    = 0,
#  debug    = 1,
#  info     = 2,
#  warn     = 3,
#  err      = 4,
#  critical = 5,
#  off      = 6
#
log_level: 0
