#
# Mile indexr configure
#

#
# Scainning nodes
#
node_urls: ["http://138.197.75.176:8080/v1/api",
            "https://104.248.7.135:8080/v1/api",
            "https://167.99.186.253:8080/v1/api"]

#node_urls: ["http://lotus000.testnet.mile.global/v1/api",
#            "http://lotus001.testnet.mile.global/v1/api"]

#
# Processing options
#
request_timeout: 50 # msec.
update_timeout:  20  # sec.
rpc_queue_size:  20
block_processin_queue_size: 10

#
# Db connection
#
db_host: "localhost"
db_port: 28015
db_name: "blockchain"

#
# Debug
#
json_rpc_debug: true

#
# Logging levels:
#
#  trace = 0,
#  debug = 1,
#  info = 2,
#  warn = 3,
#  err = 4,
#  critical = 5,
#  off = 6
#
log_level: 0
